<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Currency;

class CurrencySeeder extends Seeder
{
    public function run()
    {
        $currencies = [
            [
                'code' => 'BTC',
                'display_name' => 'Bitcoin',
                'status' => '1',
                'deposit_from_balance' => '0',
                'deposit_from_processor' => '1',
                'deposit_processor' => 'crypto',
                'deposit_min' => 0.001,
                'deposit_max' => 10,
                'deposit_fees_percentage' => 0,
                'deposit_fees_additional' => 0,
                'deposit_fees_min' => 0,
                'deposit_fees_max' => 0,
                'withdrawal_processor' => 'crypto',
                'withdrawal_min' => 0.001,
                'withdrawal_max' => 10,
                'withdrawal_fees_percentage' => 0,
                'withdrawal_fees_additional' => 0,
                'withdrawal_fees_min' => 0,
                'withdrawal_fees_max' => 0,
                'auto_withdrawal' => '0',
                'auto_withdrawal_min' => 0,
                'auto_withdrawal_max' => 0,
            ],
            [
                'code' => 'ETH',
                'display_name' => 'Ethereum',
                'status' => '1',
                'deposit_from_balance' => '0',
                'deposit_from_processor' => '1',
                'deposit_processor' => 'crypto',
                'deposit_min' => 0.01,
                'deposit_max' => 100,
                'deposit_fees_percentage' => 0,
                'deposit_fees_additional' => 0,
                'deposit_fees_min' => 0,
                'deposit_fees_max' => 0,
                'withdrawal_processor' => 'crypto',
                'withdrawal_min' => 0.01,
                'withdrawal_max' => 100,
                'withdrawal_fees_percentage' => 0,
                'withdrawal_fees_additional' => 0,
                'withdrawal_fees_min' => 0,
                'withdrawal_fees_max' => 0,
                'auto_withdrawal' => '0',
                'auto_withdrawal_min' => 0,
                'auto_withdrawal_max' => 0,
            ],
            [
                'code' => 'USDT',
                'display_name' => 'USDT (TRC20)',
                'status' => '1',
                'deposit_from_balance' => '0',
                'deposit_from_processor' => '1',
                'deposit_processor' => 'crypto',
                'deposit_min' => 10,
                'deposit_max' => 10000,
                'deposit_fees_percentage' => 0,
                'deposit_fees_additional' => 0,
                'deposit_fees_min' => 0,
                'deposit_fees_max' => 0,
                'withdrawal_processor' => 'crypto',
                'withdrawal_min' => 10,
                'withdrawal_max' => 10000,
                'withdrawal_fees_percentage' => 0,
                'withdrawal_fees_additional' => 0,
                'withdrawal_fees_min' => 0,
                'withdrawal_fees_max' => 0,
                'auto_withdrawal' => '0',
                'auto_withdrawal_min' => 0,
                'auto_withdrawal_max' => 0,
            ],
            [
                'code' => 'DOGE',
                'display_name' => 'Dogecoin',
                'status' => '1',
                'deposit_from_balance' => '0',
                'deposit_from_processor' => '1',
                'deposit_processor' => 'crypto',
                'deposit_min' => 100,
                'deposit_max' => 1000000,
                'deposit_fees_percentage' => 0,
                'deposit_fees_additional' => 0,
                'deposit_fees_min' => 0,
                'deposit_fees_max' => 0,
                'withdrawal_processor' => 'crypto',
                'withdrawal_min' => 100,
                'withdrawal_max' => 1000000,
                'withdrawal_fees_percentage' => 0,
                'withdrawal_fees_additional' => 0,
                'withdrawal_fees_min' => 0,
                'withdrawal_fees_max' => 0,
                'auto_withdrawal' => '0',
                'auto_withdrawal_min' => 0,
                'auto_withdrawal_max' => 0,
            ],
            [
                'code' => 'TRX',
                'display_name' => 'Tron (TRX)',
                'status' => '1',
                'deposit_from_balance' => '0',
                'deposit_from_processor' => '1',
                'deposit_processor' => 'crypto',
                'deposit_min' => 100,
                'deposit_max' => 1000000,
                'deposit_fees_percentage' => 0,
                'deposit_fees_additional' => 0,
                'deposit_fees_min' => 0,
                'deposit_fees_max' => 0,
                'withdrawal_processor' => 'crypto',
                'withdrawal_min' => 100,
                'withdrawal_max' => 1000000,
                'withdrawal_fees_percentage' => 0,
                'withdrawal_fees_additional' => 0,
                'withdrawal_fees_min' => 0,
                'withdrawal_fees_max' => 0,
                'auto_withdrawal' => '0',
                'auto_withdrawal_min' => 0,
                'auto_withdrawal_max' => 0,
            ],
            [
                'code' => 'BNB',
                'display_name' => 'BNB Smart Chain',
                'status' => '1',
                'deposit_from_balance' => '0',
                'deposit_from_processor' => '1',
                'deposit_processor' => 'crypto',
                'deposit_min' => 0.01,
                'deposit_max' => 100,
                'deposit_fees_percentage' => 0,
                'deposit_fees_additional' => 0,
                'deposit_fees_min' => 0,
                'deposit_fees_max' => 0,
                'withdrawal_processor' => 'crypto',
                'withdrawal_min' => 0.01,
                'withdrawal_max' => 100,
                'withdrawal_fees_percentage' => 0,
                'withdrawal_fees_additional' => 0,
                'withdrawal_fees_min' => 0,
                'withdrawal_fees_max' => 0,
                'auto_withdrawal' => '0',
                'auto_withdrawal_min' => 0,
                'auto_withdrawal_max' => 0,
            ],
            [
                'code' => 'USDT_ERC',
                'display_name' => 'USDT (ERC20)',
                'status' => '1',
                'deposit_from_balance' => '0',
                'deposit_from_processor' => '1',
                'deposit_processor' => 'crypto',
                'deposit_min' => 10,
                'deposit_max' => 10000,
                'deposit_fees_percentage' => 0,
                'deposit_fees_additional' => 0,
                'deposit_fees_min' => 0,
                'deposit_fees_max' => 0,
                'withdrawal_processor' => 'crypto',
                'withdrawal_min' => 10,
                'withdrawal_max' => 10000,
                'withdrawal_fees_percentage' => 0,
                'withdrawal_fees_additional' => 0,
                'withdrawal_fees_min' => 0,
                'withdrawal_fees_max' => 0,
                'auto_withdrawal' => '0',
                'auto_withdrawal_min' => 0,
                'auto_withdrawal_max' => 0,
            ],
        ];

        foreach ($currencies as $currency) {
            Currency::updateOrCreate(
                ['code' => $currency['code']],
                $currency
            );
        }
    }
}
